### ISSUE TITLE
Initializing Database with autocreate=false leads to errors in create_database

### ISSUE THREAD

**Issue by M1hacka** [Infinidat/infi.clickhouse_orm#78]
Hi.
What I wanted was to init Database object without creating database (it may exist or not) and then call `db.create_database()` which will create it if not already exists. Supprise:
```python
# Create database object
db = Database('test', autocreate=False)

# Create database, it doesn't exist at the moment
db.create_database()
# And...
# infi.clickhouse_orm.database.ServerError: Database test doesn't exist (81)
# Serious?
```
The problem is that when autocreate is False, flag db.db_exists is True. But it's not correct - it's value is unknown on object init. Ok, I add db.db_exists = False before create and get:
```python
# Create database, it doesn't exist at the moment
db.db_exists = False
db.create_database()
# infi.clickhouse_orm.database.DatabaseException: Custom partitioning is not supported before ClickHouse 1.1.54310. Please update your server or use date_col syntax.https://clickhouse.yandex/docs/en/table_engines/custom_partitioning_key/
```
But I know my clickhouse support it! I have version 1.1.54388. The reason of this error, is that server version was fetched once in init, it returned error (no database found) and set version to 1.1.0. I suppose, it's reasonable to update server version after database creation.

**Comment by ishirav** [comment]
I agree that it's a bug.
But what is the reasoning behind using autocreate=False and then running create_database, instead of just using autocreate=True?

**Comment by M1hacka** [comment]
I've written a ClickHouseTestCase for django that creates test database and drops it at the end of tests. It has common structure (not only ClickHouseTestCase I have):
```python
class ClickHouseTestCase(AbstractTestCase):
    @classmethod
    def get_overridden_settings(cls, worker_index: int = 0, db_prefix: str = 'test_'):
        # This method forms a dictionary of settings to override for test. 
        # In my project CLICKHOUSE_DB is set in settings, so I have to create Database object here. 
        # But I don't want to create database here, as this method may be used for other purposes
        # (for example, to clean up all test databases. It would be strange to create db in order to drop it)
        return {} # some code here

    @classmethod
    def get_databases(cls, worker_index: int = 0, db_prefix: str = 'test_'):
        # Now I have single ClickHouse database. 
        # But it may be changed in future, and method returns multiple database descriptors to pass to other methods.  
        # It may also be used in procedures that doesn't need db creation.
        cfg = cls.get_overridden_settings(worker_index=worker_index, db_prefix=db_prefix)
        return [cfg['CLICKHOUSE_DB']]

    @classmethod
    def migrate_database(cls, db)
       # This method creates database if needed and migrates it by db objects returned by get_databases()
       # db for this TestCase is infi.clickhouse_orm.Database() object.
       db.create_database() 
       # some migrate code here
```

**Comment by ishirav** [comment]
Fixed in v1.0.2

**Comment by M1hacka** [comment]
Hi.
Bug still partially exists when readonly=True. autocreate doesn't affect this situation leading to exception:
https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/src/infi/clickhouse_orm/database.py#L115
But I don't want to create database (in readonly mode it would be strange) here, only initialize Database object.

**Comment by ishirav** [comment]
What is the use case for having a database object that points to a non-existent database?

**Comment by M1hacka** [comment]
In [django-clickhouse](https://github.com/carrotquest/django-clickhouse) I give ability to configure multiple databases in settings as django does. Some of them may be readonly, others - not. There is a connection proxy class, giving ability to get database instance by alias name as well as django does.
When I start doing migrations, I iterate configured databases one by one to create them (if needed) and migrate.
The problem occures when I point same database twice - for instance, readonly and writeonly connections and readonly goes first. At this moment database is not created yet and creating `Database` instance throws an exception, while I should just skip it.
